name: Setup Branch Protection

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/setup-branch-protection.yml'

jobs:
  setup-protection:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      administration: write
      
    steps:
      - name: Setup branch protection for master
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'master',
                required_status_checks: {
                  strict: true,
                  contexts: [
                    'code-quality',
                    'test-coverage'
                  ]
                },
                enforce_admins: false,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: false,
                  require_last_push_approval: false
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false,
                block_creations: false,
                required_conversation_resolution: true,
                lock_branch: false,
                allow_fork_syncing: true
              });
              
              console.log('✅ Branch protection rules applied successfully');
              
              // Log the current protection settings
              const protection = await github.rest.repos.getBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'master'
              });
              
              console.log('Current protection settings:', JSON.stringify(protection.data, null, 2));
              
            } catch (error) {
              console.error('❌ Failed to set up branch protection:', error.message);
              
              if (error.status === 403) {
                console.log('💡 This might be due to insufficient permissions. Please ensure:');
                console.log('   - You have admin rights to the repository');
                console.log('   - The GITHUB_TOKEN has appropriate permissions');
              }
              
              throw error;
            }